export default [
    'Amanight',
    'Barnacle',
    'Blobulous',
    'Build-a-Tyrant',
    'Drellen',
    'Duster',
    'Gendricks',
    'Goblin King',
    'Goblin Queen',
    'Kollossum',
    'Leech',
    'Locgear',
    'Marrow',
    'Mulmesh',
    'Nobulous',
    'Nom',
    'Oxide',
    'Vol\'Kesh'
]
